package com.blog.dao;

import com.blog.entity.BowenClassification;
import org.springframework.stereotype.Repository;

@Repository
public interface BowenClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int deleteByPrimaryKey(Integer bowencategoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insert(BowenClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insertSelective(BowenClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    BowenClassification selectByPrimaryKey(Integer bowencategoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKeySelective(BowenClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen_classification
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKey(BowenClassification record);
}