package com.blog.dao;

import com.blog.entity.Bowen;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BowenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int deleteByPrimaryKey(Integer bowenid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insert(Bowen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insertSelective(Bowen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    Bowen selectByPrimaryKey(Integer bowenid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKeySelective(Bowen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bowen
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKey(Bowen record);

    List<Bowen> selectAll();
}