package com.blog.dao;

import com.blog.entity.LeaveMessage;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LeaveMessageMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int deleteByPrimaryKey(Integer leaveamessageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insert(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insertSelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    LeaveMessage selectByPrimaryKey(Integer leaveamessageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKeySelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKey(LeaveMessage record);

    List<LeaveMessage> selectAll();

    int updateSelfAddByPrimaryKey(LeaveMessage record);
}