package com.blog.dao;

import com.blog.entity.LeaveMessageComment;
import org.springframework.stereotype.Repository;

@Repository
public interface LeaveMessageCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    int insert(LeaveMessageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    int insertSelective(LeaveMessageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    LeaveMessageComment selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    int updateByPrimaryKeySelective(LeaveMessageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message_comment
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    int updateByPrimaryKey(LeaveMessageComment record);


    LeaveMessageComment selectByUserId(int leaveMessageId,int userId );

}