package com.blog.dao;

import com.blog.entity.PersonalDiary;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PersonalDiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int deleteByPrimaryKey(Integer diaryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insert(PersonalDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insertSelective(PersonalDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    List<PersonalDiary> selectAll(int start,int end);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKeySelective(PersonalDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_diary
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKey(PersonalDiary record);

    int selectAllCount();
}