package com.blog.dao;

import com.blog.entity.UserAlbum;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int deleteByPrimaryKey(Integer albumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insert(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int insertSelective(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    UserAlbum selectByPrimaryKey(Integer albumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKeySelective(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    int updateByPrimaryKey(UserAlbum record);


    List<UserAlbum> selectByAll();
}