package com.blog.entity;

import org.springframework.stereotype.Repository;

@Repository
public class BowenClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_classification.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer bowencategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_classification.bowenCategoryName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String bowencategoryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_classification.bowenCategoryId
     *
     * @return the value of bowen_classification.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getBowencategoryid() {
        return bowencategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_classification.bowenCategoryId
     *
     * @param bowencategoryid the value for bowen_classification.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowencategoryid(Integer bowencategoryid) {
        this.bowencategoryid = bowencategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_classification.bowenCategoryName
     *
     * @return the value of bowen_classification.bowenCategoryName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getBowencategoryname() {
        return bowencategoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_classification.bowenCategoryName
     *
     * @param bowencategoryname the value for bowen_classification.bowenCategoryName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowencategoryname(String bowencategoryname) {
        this.bowencategoryname = bowencategoryname == null ? null : bowencategoryname.trim();
    }
}