package com.blog.entity;

import org.springframework.stereotype.Repository;

@Repository
public class BowenAppreciation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_appreciation.appreciationId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer appreciationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_appreciation.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_appreciation.appreciationContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String appreciationcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_appreciation.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer procrastination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen_appreciation.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer low;

    private Integer bowenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_appreciation.appreciationId
     *
     * @return the value of bowen_appreciation.appreciationId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getAppreciationid() {
        return appreciationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_appreciation.appreciationId
     *
     * @param appreciationid the value for bowen_appreciation.appreciationId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setAppreciationid(Integer appreciationid) {
        this.appreciationid = appreciationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_appreciation.userId
     *
     * @return the value of bowen_appreciation.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_appreciation.userId
     *
     * @param userid the value for bowen_appreciation.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_appreciation.appreciationContent
     *
     * @return the value of bowen_appreciation.appreciationContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getAppreciationcontent() {
        return appreciationcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_appreciation.appreciationContent
     *
     * @param appreciationcontent the value for bowen_appreciation.appreciationContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setAppreciationcontent(String appreciationcontent) {
        this.appreciationcontent = appreciationcontent == null ? null : appreciationcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_appreciation.procrastination
     *
     * @return the value of bowen_appreciation.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getProcrastination() {
        return procrastination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_appreciation.procrastination
     *
     * @param procrastination the value for bowen_appreciation.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setProcrastination(Integer procrastination) {
        this.procrastination = procrastination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen_appreciation.low
     *
     * @return the value of bowen_appreciation.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen_appreciation.low
     *
     * @param low the value for bowen_appreciation.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setLow(Integer low) {
        this.low = low;
    }

    public Integer getBowenid() {
        return bowenid;
    }

    public void setBowenid(Integer bowenid) {
        this.bowenid = bowenid;
    }
}