package com.blog.entity;

import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public class Bowen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer bowenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenTitle
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String bowentitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String bowencontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenImag
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String bowenimag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer bowencategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bowen.bowenCreateTime
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Date bowencreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenId
     *
     * @return the value of bowen.bowenId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getBowenid() {
        return bowenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenId
     *
     * @param bowenid the value for bowen.bowenId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowenid(Integer bowenid) {
        this.bowenid = bowenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.userId
     *
     * @return the value of bowen.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.userId
     *
     * @param userid the value for bowen.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenTitle
     *
     * @return the value of bowen.bowenTitle
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getBowentitle() {
        return bowentitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenTitle
     *
     * @param bowentitle the value for bowen.bowenTitle
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowentitle(String bowentitle) {
        this.bowentitle = bowentitle == null ? null : bowentitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenContent
     *
     * @return the value of bowen.bowenContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getBowencontent() {
        return bowencontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenContent
     *
     * @param bowencontent the value for bowen.bowenContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowencontent(String bowencontent) {
        this.bowencontent = bowencontent == null ? null : bowencontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenImag
     *
     * @return the value of bowen.bowenImag
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getBowenimag() {
        return bowenimag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenImag
     *
     * @param bowenimag the value for bowen.bowenImag
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowenimag(String bowenimag) {
        this.bowenimag = bowenimag == null ? null : bowenimag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenCategoryId
     *
     * @return the value of bowen.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getBowencategoryid() {
        return bowencategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenCategoryId
     *
     * @param bowencategoryid the value for bowen.bowenCategoryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowencategoryid(Integer bowencategoryid) {
        this.bowencategoryid = bowencategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bowen.bowenCreateTime
     *
     * @return the value of bowen.bowenCreateTime
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Date getBowencreatetime() {
        return bowencreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bowen.bowenCreateTime
     *
     * @param bowencreatetime the value for bowen.bowenCreateTime
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setBowencreatetime(Date bowencreatetime) {
        this.bowencreatetime = bowencreatetime;
    }
}