package com.blog.entity;

import org.springframework.stereotype.Repository;

import java.io.Serializable;

@Repository

public class IllegalKeywords implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_keywords.keywordsId
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    private Integer keywordsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_keywords.keywords
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    private String keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_keywords.keywordsId
     *
     * @return the value of illegal_keywords.keywordsId
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    public Integer getKeywordsid() {
        return keywordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_keywords.keywordsId
     *
     * @param keywordsid the value for illegal_keywords.keywordsId
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    public void setKeywordsid(Integer keywordsid) {
        this.keywordsid = keywordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_keywords.keywords
     *
     * @return the value of illegal_keywords.keywords
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_keywords.keywords
     *
     * @param keywords the value for illegal_keywords.keywords
     *
     * @mbggenerated Sun Jun 25 18:25:18 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }



}