package com.blog.entity;

import org.springframework.stereotype.Repository;

@Repository
public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.imageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer imageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.albumId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer albumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.amagePaht
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String amagepaht;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.imageId
     *
     * @return the value of image.imageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.imageId
     *
     * @param imageid the value for image.imageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.albumId
     *
     * @return the value of image.albumId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.albumId
     *
     * @param albumid the value for image.albumId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setAlbumid(Integer albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.amagePaht
     *
     * @return the value of image.amagePaht
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getAmagepaht() {
        return amagepaht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.amagePaht
     *
     * @param amagepaht the value for image.amagePaht
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setAmagepaht(String amagepaht) {
        this.amagepaht = amagepaht == null ? null : amagepaht.trim();
    }
}