package com.blog.entity;

import org.springframework.stereotype.Repository;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

@Repository
public class LeaveMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.leaveAMessageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer leaveamessageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.sendMessageUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer sendmessageuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.sendMassageUserName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String sendmassageusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.receiveUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer receiveuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.leaveAmessageContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String leaveamessagecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer procrastination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer low;

    public Timestamp leavemessagetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.leaveAMessageId
     *
     * @return the value of leave_message.leaveAMessageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getLeaveamessageid() {
        return leaveamessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.leaveAMessageId
     *
     * @param leaveamessageid the value for leave_message.leaveAMessageId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */


    public void setLeaveamessageid(Integer leaveamessageid) {
        this.leaveamessageid = leaveamessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.sendMessageUserId
     *
     * @return the value of leave_message.sendMessageUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getSendmessageuserid() {
        return sendmessageuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.sendMessageUserId
     *
     * @param sendmessageuserid the value for leave_message.sendMessageUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setSendmessageuserid(Integer sendmessageuserid) {
        this.sendmessageuserid = sendmessageuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.sendMassageUserName
     *
     * @return the value of leave_message.sendMassageUserName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getSendmassageusername() {
        return sendmassageusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.sendMassageUserName
     *
     * @param sendmassageusername the value for leave_message.sendMassageUserName
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setSendmassageusername(String sendmassageusername) {
        this.sendmassageusername = sendmassageusername == null ? null : sendmassageusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.receiveUserId
     *
     * @return the value of leave_message.receiveUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getReceiveuserid() {
        return receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.receiveUserId
     *
     * @param receiveuserid the value for leave_message.receiveUserId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setReceiveuserid(Integer receiveuserid) {
        this.receiveuserid = receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.leaveAmessageContent
     *
     * @return the value of leave_message.leaveAmessageContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getLeaveamessagecontent() {
        return leaveamessagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.leaveAmessageContent
     *
     * @param leaveamessagecontent the value for leave_message.leaveAmessageContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setLeaveamessagecontent(String leaveamessagecontent) {
        this.leaveamessagecontent = leaveamessagecontent == null ? null : leaveamessagecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.procrastination
     *
     * @return the value of leave_message.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getProcrastination() {
        return procrastination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.procrastination
     *
     * @param procrastination the value for leave_message.procrastination
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setProcrastination(Integer procrastination) {
        this.procrastination = procrastination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message.low
     *
     * @return the value of leave_message.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message.low
     *
     * @param low the value for leave_message.low
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setLow(Integer low) {
        this.low = low;
    }

    public Timestamp getLeavemessagetime() {
        return leavemessagetime;
    }

    public void setLeavemessagetime(Timestamp leavemessagetime) {
        this.leavemessagetime = leavemessagetime;
    }
}