package com.blog.entity;

import org.springframework.stereotype.Repository;

@Repository
public class LeaveMessageComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message_comment.CommentId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message_comment.leaveAMessageId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    private Integer leaveamessageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_message_comment.userId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message_comment.CommentId
     *
     * @return the value of leave_message_comment.CommentId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message_comment.CommentId
     *
     * @param commentid the value for leave_message_comment.CommentId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message_comment.leaveAMessageId
     *
     * @return the value of leave_message_comment.leaveAMessageId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public Integer getLeaveamessageid() {
        return leaveamessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message_comment.leaveAMessageId
     *
     * @param leaveamessageid the value for leave_message_comment.leaveAMessageId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public void setLeaveamessageid(Integer leaveamessageid) {
        this.leaveamessageid = leaveamessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_message_comment.userId
     *
     * @return the value of leave_message_comment.userId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_message_comment.userId
     *
     * @param userid the value for leave_message_comment.userId
     *
     * @mbggenerated Sun Jun 25 00:46:39 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}