package com.blog.entity;

import org.springframework.stereotype.Repository;

@Repository
public class PersonalDiary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_diary.diaryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer diaryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_diary.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_diary.diaryIdContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    private String diaryidcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_diary.diaryId
     *
     * @return the value of personal_diary.diaryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getDiaryid() {
        return diaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_diary.diaryId
     *
     * @param diaryid the value for personal_diary.diaryId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setDiaryid(Integer diaryid) {
        this.diaryid = diaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_diary.userId
     *
     * @return the value of personal_diary.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_diary.userId
     *
     * @param userid the value for personal_diary.userId
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_diary.diaryIdContent
     *
     * @return the value of personal_diary.diaryIdContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public String getDiaryidcontent() {
        return diaryidcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_diary.diaryIdContent
     *
     * @param diaryidcontent the value for personal_diary.diaryIdContent
     *
     * @mbggenerated Fri Jun 23 16:50:23 CST 2017
     */
    public void setDiaryidcontent(String diaryidcontent) {
        this.diaryidcontent = diaryidcontent == null ? null : diaryidcontent.trim();
    }
}